/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_augmate_scany_NativeUtils */

#ifndef _Included_com_augmate_scany_NativeUtils
#define _Included_com_augmate_scany_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_augmate_scany_NativeUtils
 * Method:    binarize
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_augmate_scany_NativeUtils_binarize
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_augmate_scany_NativeUtils
 * Method:    binarizeToIntBuffer
 * Signature: ([B[III)V
 */
JNIEXPORT void JNICALL Java_com_augmate_scany_NativeUtils_binarizeToIntBuffer
  (JNIEnv *, jclass, jbyteArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
